service: presidential-fitness

# Name of the container image
image: ghcr.io/tadlambjr/presidential-fitness

servers:
  web:
    hosts:
      - roaring-lamb-staging
    options:
      memory: 512m
      memory-swap: 640m
      cpus: 0.5

proxy:
  ssl: true
  host: fitness.roaringlambproductions.com
  healthcheck:
    path: /up
    interval: 5
    timeout: 90

# GitHub Container Registry for Docker images
registry:
  server: ghcr.io
  username: tadlambjr
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    RAILS_ENV: production
    RAILS_SERVE_STATIC_FILES: true
    MALLOC_ARENA_MAX: 2
    RUBY_GC_HEAP_GROWTH_FACTOR: 1.1
    RUBY_GC_HEAP_GROWTH_MAX_SLOTS: 5000
    RUBY_GC_MALLOC_LIMIT: 16777216

# Aliases are triggered with "bin/kamal <alias>". You can overwrite arguments on invocation:
# "bin/kamal logs -r job" will tail logs from the first server in the job section.
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

volumes:
  - "/var/lib/presidential-fitness/storage:/rails/storage"
  - "/var/lib/presidential-fitness_logs:/rails/log"

# Bridge fingerprinted assets, like JS and CSS, between versions to avoid
# hitting 404 on in-flight requests. Combines all files from new and old
# version inside the asset_path.
asset_path: /rails/public/assets

builder:
  context: .
  arch: amd64
  args:
    RUBY_VERSION: 4.0.1
  secrets:
    - RAILS_MASTER_KEY

ssh:
  user: roaringlamb
